2016-03-16 10:59:42,374-app-ERROR-Exception on /test/log_test [GET]
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\flask\app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\sxchen\Desktop\GreenBeltBonusSystem-high-structual\GreenBeltBonusSystem-high-structual\app\views\views.py", line 254, in log_test
    a = None + 1
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

2016-03-18 08:20:07,086-app-ERROR-Exception on /test/log_test [GET]
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\flask\app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\sxchen\Desktop\GreenBeltBonusSystem-high-structual\GreenBeltBonusSystem-high-structual\app\views\views.py", line 254, in log_test
    a = None + 1
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
2016-03-18 09:23:17,549-app-ERROR-Exception on /test/log_test [GET]
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\flask\app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\sxchen\Desktop\GreenBeltBonusSystem-high-structual\GreenBeltBonusSystem-high-structual\app\views\views.py", line 261, in log_test
    def log_test():
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
2016-03-18 09:23:39,855-app-ERROR-Exception on /admin [POST]
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\flask\app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\sxchen\Desktop\GreenBeltBonusSystem-high-structual\GreenBeltBonusSystem-high-structual\app\views\views.py", line 152, in admin
    
IntegrityError: column PROJECT_NUMBER is not unique
2016-03-18 09:44:37,035-app-ERROR-Exception on /admin [POST]
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\flask\app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\sxchen\Desktop\GreenBeltBonusSystem-high-structual\GreenBeltBonusSystem-high-structual\app\views\views.py", line 158, in admin
    except IntegrityError,e:
NameError: global name 'IntegrityError' is not defined
2016-03-18 09:46:03,923-app-ERROR-Exception on /admin [POST]
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\flask\app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\sxchen\Desktop\GreenBeltBonusSystem-high-structual\GreenBeltBonusSystem-high-structual\app\views\views.py", line 158, in admin
    except IntegrityError,e:
NameError: global name 'IntegrityError' is not defined
2016-03-18 09:47:12,029-app-ERROR-Exception on /admin [POST]
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\flask\app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1577, in make_response
    rv = self.response_class.force_type(rv, request.environ)
  File "D:\Python27\lib\site-packages\werkzeug\wrappers.py", line 841, in force_type
    response = BaseResponse(*_run_wsgi_app(response, environ))
  File "D:\Python27\lib\site-packages\werkzeug\wrappers.py", line 57, in _run_wsgi_app
    return _run_wsgi_app(*args)
  File "D:\Python27\lib\site-packages\werkzeug\test.py", line 867, in run_wsgi_app
    app_rv = app(environ, start_response)
TypeError: 'tuple' object is not callable
2016-03-18 09:52:49,493-app-ERROR-Exception on /admin [POST]
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\flask\app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\sxchen\Desktop\GreenBeltBonusSystem-high-structual\GreenBeltBonusSystem-high-structual\app\views\views.py", line 153, in admin
    cur.execute(INSERT_PROJECT_INFO)
IntegrityError: column PROJECT_NUMBER is not unique
2016-03-18 16:54:47,280-app-ERROR-Exception on /rules [GET]
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\flask\app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\sxchen\Desktop\GreenBeltBonusSystem-high-structual\GreenBeltBonusSystem-high-structual\app\views\views.py", line 244, in rules
    return render_template('rules.html')
  File "D:\Python27\lib\site-packages\flask\templating.py", line 128, in render_template
    context, ctx.app)
  File "D:\Python27\lib\site-packages\flask\templating.py", line 110, in _render
    rv = template.render(context)
  File "D:\Python27\lib\site-packages\jinja2\environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "D:\Python27\lib\site-packages\jinja2\environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\sxchen\Desktop\GreenBeltBonusSystem-high-structual\GreenBeltBonusSystem-high-structual\app\templates\rules.html", line 16, in top-level template code
    <a href="{{ url_for('amdin') }}" style="color: white;font-size:18px;padding: 14px" class="btn">Admin</a>
  File "D:\Python27\lib\site-packages\flask\helpers.py", line 312, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1641, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "D:\Python27\lib\site-packages\flask\helpers.py", line 305, in url_for
    force_external=external)
  File "D:\Python27\lib\site-packages\werkzeug\routing.py", line 1678, in build
    raise BuildError(endpoint, values, method)
BuildError: ('amdin', {}, None)
2016-03-18 16:55:08,694-app-ERROR-Exception on /rules [GET]
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\flask\app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\sxchen\Desktop\GreenBeltBonusSystem-high-structual\GreenBeltBonusSystem-high-structual\app\views\views.py", line 244, in rules
    return render_template('rules.html')
  File "D:\Python27\lib\site-packages\flask\templating.py", line 128, in render_template
    context, ctx.app)
  File "D:\Python27\lib\site-packages\flask\templating.py", line 110, in _render
    rv = template.render(context)
  File "D:\Python27\lib\site-packages\jinja2\environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "D:\Python27\lib\site-packages\jinja2\environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\sxchen\Desktop\GreenBeltBonusSystem-high-structual\GreenBeltBonusSystem-high-structual\app\templates\rules.html", line 16, in top-level template code
    <a href="{{ url_for('amdin') }}" style="color: white;font-size:18px;padding: 14px" class="btn">Admin</a>
  File "D:\Python27\lib\site-packages\flask\helpers.py", line 312, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1641, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "D:\Python27\lib\site-packages\flask\helpers.py", line 305, in url_for
    force_external=external)
  File "D:\Python27\lib\site-packages\werkzeug\routing.py", line 1678, in build
    raise BuildError(endpoint, values, method)
BuildError: ('amdin', {}, None)
2016-03-18 16:55:29,997-app-ERROR-Exception on /rules [GET]
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\flask\app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\sxchen\Desktop\GreenBeltBonusSystem-high-structual\GreenBeltBonusSystem-high-structual\app\views\views.py", line 244, in rules
    return render_template('rules.html')
  File "D:\Python27\lib\site-packages\flask\templating.py", line 128, in render_template
    context, ctx.app)
  File "D:\Python27\lib\site-packages\flask\templating.py", line 110, in _render
    rv = template.render(context)
  File "D:\Python27\lib\site-packages\jinja2\environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "D:\Python27\lib\site-packages\jinja2\environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\sxchen\Desktop\GreenBeltBonusSystem-high-structual\GreenBeltBonusSystem-high-structual\app\templates\rules.html", line 16, in top-level template code
    <a href="{{ url_for('amdin') }}" style="color: white;font-size:18px;padding: 14px" class="btn">Admin</a>
  File "D:\Python27\lib\site-packages\flask\helpers.py", line 312, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1641, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "D:\Python27\lib\site-packages\flask\helpers.py", line 305, in url_for
    force_external=external)
  File "D:\Python27\lib\site-packages\werkzeug\routing.py", line 1678, in build
    raise BuildError(endpoint, values, method)
BuildError: ('amdin', {}, None)
2016-03-18 16:55:31,605-app-ERROR-Exception on /rules [GET]
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\flask\app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\sxchen\Desktop\GreenBeltBonusSystem-high-structual\GreenBeltBonusSystem-high-structual\app\views\views.py", line 244, in rules
    return render_template('rules.html')
  File "D:\Python27\lib\site-packages\flask\templating.py", line 128, in render_template
    context, ctx.app)
  File "D:\Python27\lib\site-packages\flask\templating.py", line 110, in _render
    rv = template.render(context)
  File "D:\Python27\lib\site-packages\jinja2\environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "D:\Python27\lib\site-packages\jinja2\environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\sxchen\Desktop\GreenBeltBonusSystem-high-structual\GreenBeltBonusSystem-high-structual\app\templates\rules.html", line 16, in top-level template code
    <a href="{{ url_for('amdin') }}" style="color: white;font-size:18px;padding: 14px" class="btn">Admin</a>
  File "D:\Python27\lib\site-packages\flask\helpers.py", line 312, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1641, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "D:\Python27\lib\site-packages\flask\helpers.py", line 305, in url_for
    force_external=external)
  File "D:\Python27\lib\site-packages\werkzeug\routing.py", line 1678, in build
    raise BuildError(endpoint, values, method)
BuildError: ('amdin', {}, None)
2016-03-24 10:52:54,684-app-ERROR-Exception on /test/log_test [GET]
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\flask\app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\sxchen\Desktop\GreenBeltBonusSystem\app\views\views.py", line 281, in log_test
    a = None + 1
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
2016-03-24 11:14:21,509-app-ERROR-Exception on /admin_test [POST]
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\flask\app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\sxchen\Desktop\GreenBeltBonusSystem\app\views\views.py", line 288, in admin_test
    request.form['xxx'] = 'xxx'
  File "D:\Python27\lib\site-packages\werkzeug\datastructures.py", line 178, in __setitem__
    is_immutable(self)
  File "D:\Python27\lib\site-packages\werkzeug\datastructures.py", line 28, in is_immutable
    raise TypeError('%r objects are immutable' % self.__class__.__name__)
TypeError: 'ImmutableMultiDict' objects are immutable
2016-03-24 11:14:27,815-app-ERROR-Exception on /admin_test [POST]
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\flask\app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\sxchen\Desktop\GreenBeltBonusSystem\app\views\views.py", line 288, in admin_test
    request.form['xxx'] = 'xxx'
  File "D:\Python27\lib\site-packages\werkzeug\datastructures.py", line 178, in __setitem__
    is_immutable(self)
  File "D:\Python27\lib\site-packages\werkzeug\datastructures.py", line 28, in is_immutable
    raise TypeError('%r objects are immutable' % self.__class__.__name__)
TypeError: 'ImmutableMultiDict' objects are immutable
2016-03-24 11:14:35,835-app-ERROR-Exception on /admin_test [POST]
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\flask\app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\sxchen\Desktop\GreenBeltBonusSystem\app\views\views.py", line 288, in admin_test
    #request.form['xxx'] = 'xxx'
  File "D:\Python27\lib\site-packages\werkzeug\datastructures.py", line 178, in __setitem__
    is_immutable(self)
  File "D:\Python27\lib\site-packages\werkzeug\datastructures.py", line 28, in is_immutable
    raise TypeError('%r objects are immutable' % self.__class__.__name__)
TypeError: 'ImmutableMultiDict' objects are immutable
2016-03-24 11:14:36,640-app-ERROR-Exception on /admin_test [POST]
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\flask\app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\sxchen\Desktop\GreenBeltBonusSystem\app\views\views.py", line 288, in admin_test
    #request.form['xxx'] = 'xxx'
  File "D:\Python27\lib\site-packages\werkzeug\datastructures.py", line 178, in __setitem__
    is_immutable(self)
  File "D:\Python27\lib\site-packages\werkzeug\datastructures.py", line 28, in is_immutable
    raise TypeError('%r objects are immutable' % self.__class__.__name__)
TypeError: 'ImmutableMultiDict' objects are immutable
2016-03-24 11:14:36,871-app-ERROR-Exception on /admin_test [POST]
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\flask\app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\sxchen\Desktop\GreenBeltBonusSystem\app\views\views.py", line 288, in admin_test
    #request.form['xxx'] = 'xxx'
  File "D:\Python27\lib\site-packages\werkzeug\datastructures.py", line 178, in __setitem__
    is_immutable(self)
  File "D:\Python27\lib\site-packages\werkzeug\datastructures.py", line 28, in is_immutable
    raise TypeError('%r objects are immutable' % self.__class__.__name__)
TypeError: 'ImmutableMultiDict' objects are immutable
2016-03-24 11:14:37,059-app-ERROR-Exception on /admin_test [POST]
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\flask\app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\sxchen\Desktop\GreenBeltBonusSystem\app\views\views.py", line 288, in admin_test
    #request.form['xxx'] = 'xxx'
  File "D:\Python27\lib\site-packages\werkzeug\datastructures.py", line 178, in __setitem__
    is_immutable(self)
  File "D:\Python27\lib\site-packages\werkzeug\datastructures.py", line 28, in is_immutable
    raise TypeError('%r objects are immutable' % self.__class__.__name__)
TypeError: 'ImmutableMultiDict' objects are immutable
2016-03-24 11:15:27,608-app-ERROR-Exception on /api/user/ [GET]
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\flask\app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\sxchen\Desktop\GreenBeltBonusSystem\app\views\views.py", line 257, in user
    SEARCH_NAME = sql.SEARCH_NAME % (n, n)
NameError: global name 'sql' is not defined
2016-03-24 11:16:10,862-app-ERROR-Exception on /admin_test [POST]
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\flask\app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\sxchen\Desktop\GreenBeltBonusSystem\app\views\views.py", line 288, in admin_test
    request.form['xxx'] = 'xxx'
  File "D:\Python27\lib\site-packages\werkzeug\datastructures.py", line 178, in __setitem__
    is_immutable(self)
  File "D:\Python27\lib\site-packages\werkzeug\datastructures.py", line 28, in is_immutable
    raise TypeError('%r objects are immutable' % self.__class__.__name__)
TypeError: 'ImmutableMultiDict' objects are immutable
2016-03-24 18:16:07,147-app-ERROR-Exception on /admin [GET]
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\flask\app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\sxchen\Desktop\GreenBeltBonusSystem\app\views\views.py", line 180, in admin
    insert_records.insert_month_3_release(g.conn, project_num, '6 month closed')
  File "D:\Python27\lib\site-packages\flask\templating.py", line 128, in render_template
    context, ctx.app)
  File "D:\Python27\lib\site-packages\flask\templating.py", line 110, in _render
    rv = template.render(context)
  File "D:\Python27\lib\site-packages\jinja2\environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "D:\Python27\lib\site-packages\jinja2\environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\sxchen\Desktop\GreenBeltBonusSystem\app\templates\admin.html", line 59, in top-level template code
    <option value="{{ data.duplicability.level3 }}">{{ data.duplicability.level3 }} >2 Workshop</option>
  File "D:\Python27\lib\site-packages\jinja2\environment.py", line 408, in getattr
    return getattr(obj, attribute)
UndefinedError: 'data' is undefined
2016-03-24 18:17:01,670-app-ERROR-Exception on /admin [GET]
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\flask\app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\sxchen\Desktop\GreenBeltBonusSystem\app\views\views.py", line 180, in admin
    insert_records.insert_month_3_release(g.conn, project_num, '6 month closed')
  File "D:\Python27\lib\site-packages\flask\templating.py", line 128, in render_template
    context, ctx.app)
  File "D:\Python27\lib\site-packages\flask\templating.py", line 110, in _render
    rv = template.render(context)
  File "D:\Python27\lib\site-packages\jinja2\environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "D:\Python27\lib\site-packages\jinja2\environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\sxchen\Desktop\GreenBeltBonusSystem\app\templates\admin.html", line 59, in top-level template code
    <option value="{{ data.duplicability.level3 }}">{{ data.duplicability.level3 }} >2 Workshop</option>
  File "D:\Python27\lib\site-packages\jinja2\environment.py", line 408, in getattr
    return getattr(obj, attribute)
UndefinedError: 'data' is undefined
2016-03-25 13:58:50,588-app-ERROR-Exception on /search [POST]
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\flask\app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\sxchen\Desktop\GreenBeltBonusSystem\app\views\views.py", line 75, in search
    res2 = ts.summary(g.conn)
  File "C:\Users\sxchen\Desktop\GreenBeltBonusSystem\app\ext\totalSummary.py", line 95, in summary
    report = report_html()
TypeError: __init__() takes exactly 4 arguments (1 given)
2016-03-25 14:00:11,141-app-ERROR-Exception on /search [POST]
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\flask\app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\sxchen\Desktop\GreenBeltBonusSystem\app\views\views.py", line 75, in search
    res2 = ts.summary(g.conn)
  File "C:\Users\sxchen\Desktop\GreenBeltBonusSystem\app\ext\totalSummary.py", line 95, in summary
    report = report_html()
TypeError: __init__() takes exactly 4 arguments (1 given)
2016-03-25 14:04:42,081-app-ERROR-Exception on /search [POST]
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\flask\app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\sxchen\Desktop\GreenBeltBonusSystem\app\views\views.py", line 75, in search
    res2 = ts.summary(g.conn)
  File "C:\Users\sxchen\Desktop\GreenBeltBonusSystem\app\ext\totalSummary.py", line 95, in summary
    report = report_html(conn=conn,month_begin=None,month_end=None)
TypeError: __init__() takes exactly 4 arguments (1 given)
2016-03-25 14:05:06,039-app-ERROR-Exception on /search [POST]
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\flask\app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\sxchen\Desktop\GreenBeltBonusSystem\app\views\views.py", line 75, in search
    res2 = ts.summary(g.conn)
  File "C:\Users\sxchen\Desktop\GreenBeltBonusSystem\app\ext\totalSummary.py", line 121, in summary
    d6=round(d6,1),
NameError: global name 'd6' is not defined
2016-03-25 14:05:36,865-app-ERROR-Exception on /search [POST]
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\flask\app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\sxchen\Desktop\GreenBeltBonusSystem\app\views\views.py", line 75, in search
    res2 = ts.summary(g.conn)
  File "C:\Users\sxchen\Desktop\GreenBeltBonusSystem\app\ext\totalSummary.py", line 121, in summary
NameError: global name 'd6' is not defined
2016-03-25 14:08:49,223-app-ERROR-Exception on /search [POST]
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\flask\app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\sxchen\Desktop\GreenBeltBonusSystem\app\views\views.py", line 75, in search
    ts = totalSummary(employee_name)
  File "C:\Users\sxchen\Desktop\GreenBeltBonusSystem\app\ext\totalSummary.py", line 121, in summary
NameError: global name 'd6' is not defined
