2016-03-16 10:59:42,374-app-ERROR-Exception on /test/log_test [GET]
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\flask\app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\sxchen\Desktop\GreenBeltBonusSystem-high-structual\GreenBeltBonusSystem-high-structual\app\views\views.py", line 254, in log_test
    a = None + 1
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

2016-03-18 08:20:07,086-app-ERROR-Exception on /test/log_test [GET]
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\flask\app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\sxchen\Desktop\GreenBeltBonusSystem-high-structual\GreenBeltBonusSystem-high-structual\app\views\views.py", line 254, in log_test
    a = None + 1
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
2016-03-18 09:23:17,549-app-ERROR-Exception on /test/log_test [GET]
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\flask\app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\sxchen\Desktop\GreenBeltBonusSystem-high-structual\GreenBeltBonusSystem-high-structual\app\views\views.py", line 261, in log_test
    def log_test():
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
2016-03-18 09:23:39,855-app-ERROR-Exception on /admin [POST]
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\flask\app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\sxchen\Desktop\GreenBeltBonusSystem-high-structual\GreenBeltBonusSystem-high-structual\app\views\views.py", line 152, in admin
    
IntegrityError: column PROJECT_NUMBER is not unique
2016-03-18 09:44:37,035-app-ERROR-Exception on /admin [POST]
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\flask\app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\sxchen\Desktop\GreenBeltBonusSystem-high-structual\GreenBeltBonusSystem-high-structual\app\views\views.py", line 158, in admin
    except IntegrityError,e:
NameError: global name 'IntegrityError' is not defined
2016-03-18 09:46:03,923-app-ERROR-Exception on /admin [POST]
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\flask\app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\sxchen\Desktop\GreenBeltBonusSystem-high-structual\GreenBeltBonusSystem-high-structual\app\views\views.py", line 158, in admin
    except IntegrityError,e:
NameError: global name 'IntegrityError' is not defined
2016-03-18 09:47:12,029-app-ERROR-Exception on /admin [POST]
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\flask\app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1577, in make_response
    rv = self.response_class.force_type(rv, request.environ)
  File "D:\Python27\lib\site-packages\werkzeug\wrappers.py", line 841, in force_type
    response = BaseResponse(*_run_wsgi_app(response, environ))
  File "D:\Python27\lib\site-packages\werkzeug\wrappers.py", line 57, in _run_wsgi_app
    return _run_wsgi_app(*args)
  File "D:\Python27\lib\site-packages\werkzeug\test.py", line 867, in run_wsgi_app
    app_rv = app(environ, start_response)
TypeError: 'tuple' object is not callable
2016-03-18 09:52:49,493-app-ERROR-Exception on /admin [POST]
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\flask\app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\sxchen\Desktop\GreenBeltBonusSystem-high-structual\GreenBeltBonusSystem-high-structual\app\views\views.py", line 153, in admin
    cur.execute(INSERT_PROJECT_INFO)
IntegrityError: column PROJECT_NUMBER is not unique
2016-03-18 16:54:47,280-app-ERROR-Exception on /rules [GET]
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\flask\app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\sxchen\Desktop\GreenBeltBonusSystem-high-structual\GreenBeltBonusSystem-high-structual\app\views\views.py", line 244, in rules
    return render_template('rules.html')
  File "D:\Python27\lib\site-packages\flask\templating.py", line 128, in render_template
    context, ctx.app)
  File "D:\Python27\lib\site-packages\flask\templating.py", line 110, in _render
    rv = template.render(context)
  File "D:\Python27\lib\site-packages\jinja2\environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "D:\Python27\lib\site-packages\jinja2\environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\sxchen\Desktop\GreenBeltBonusSystem-high-structual\GreenBeltBonusSystem-high-structual\app\templates\rules.html", line 16, in top-level template code
    <a href="{{ url_for('amdin') }}" style="color: white;font-size:18px;padding: 14px" class="btn">Admin</a>
  File "D:\Python27\lib\site-packages\flask\helpers.py", line 312, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1641, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "D:\Python27\lib\site-packages\flask\helpers.py", line 305, in url_for
    force_external=external)
  File "D:\Python27\lib\site-packages\werkzeug\routing.py", line 1678, in build
    raise BuildError(endpoint, values, method)
BuildError: ('amdin', {}, None)
2016-03-18 16:55:08,694-app-ERROR-Exception on /rules [GET]
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\flask\app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\sxchen\Desktop\GreenBeltBonusSystem-high-structual\GreenBeltBonusSystem-high-structual\app\views\views.py", line 244, in rules
    return render_template('rules.html')
  File "D:\Python27\lib\site-packages\flask\templating.py", line 128, in render_template
    context, ctx.app)
  File "D:\Python27\lib\site-packages\flask\templating.py", line 110, in _render
    rv = template.render(context)
  File "D:\Python27\lib\site-packages\jinja2\environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "D:\Python27\lib\site-packages\jinja2\environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\sxchen\Desktop\GreenBeltBonusSystem-high-structual\GreenBeltBonusSystem-high-structual\app\templates\rules.html", line 16, in top-level template code
    <a href="{{ url_for('amdin') }}" style="color: white;font-size:18px;padding: 14px" class="btn">Admin</a>
  File "D:\Python27\lib\site-packages\flask\helpers.py", line 312, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1641, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "D:\Python27\lib\site-packages\flask\helpers.py", line 305, in url_for
    force_external=external)
  File "D:\Python27\lib\site-packages\werkzeug\routing.py", line 1678, in build
    raise BuildError(endpoint, values, method)
BuildError: ('amdin', {}, None)
2016-03-18 16:55:29,997-app-ERROR-Exception on /rules [GET]
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\flask\app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\sxchen\Desktop\GreenBeltBonusSystem-high-structual\GreenBeltBonusSystem-high-structual\app\views\views.py", line 244, in rules
    return render_template('rules.html')
  File "D:\Python27\lib\site-packages\flask\templating.py", line 128, in render_template
    context, ctx.app)
  File "D:\Python27\lib\site-packages\flask\templating.py", line 110, in _render
    rv = template.render(context)
  File "D:\Python27\lib\site-packages\jinja2\environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "D:\Python27\lib\site-packages\jinja2\environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\sxchen\Desktop\GreenBeltBonusSystem-high-structual\GreenBeltBonusSystem-high-structual\app\templates\rules.html", line 16, in top-level template code
    <a href="{{ url_for('amdin') }}" style="color: white;font-size:18px;padding: 14px" class="btn">Admin</a>
  File "D:\Python27\lib\site-packages\flask\helpers.py", line 312, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1641, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "D:\Python27\lib\site-packages\flask\helpers.py", line 305, in url_for
    force_external=external)
  File "D:\Python27\lib\site-packages\werkzeug\routing.py", line 1678, in build
    raise BuildError(endpoint, values, method)
BuildError: ('amdin', {}, None)
2016-03-18 16:55:31,605-app-ERROR-Exception on /rules [GET]
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\flask\app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\sxchen\Desktop\GreenBeltBonusSystem-high-structual\GreenBeltBonusSystem-high-structual\app\views\views.py", line 244, in rules
    return render_template('rules.html')
  File "D:\Python27\lib\site-packages\flask\templating.py", line 128, in render_template
    context, ctx.app)
  File "D:\Python27\lib\site-packages\flask\templating.py", line 110, in _render
    rv = template.render(context)
  File "D:\Python27\lib\site-packages\jinja2\environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "D:\Python27\lib\site-packages\jinja2\environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\sxchen\Desktop\GreenBeltBonusSystem-high-structual\GreenBeltBonusSystem-high-structual\app\templates\rules.html", line 16, in top-level template code
    <a href="{{ url_for('amdin') }}" style="color: white;font-size:18px;padding: 14px" class="btn">Admin</a>
  File "D:\Python27\lib\site-packages\flask\helpers.py", line 312, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1641, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "D:\Python27\lib\site-packages\flask\helpers.py", line 305, in url_for
    force_external=external)
  File "D:\Python27\lib\site-packages\werkzeug\routing.py", line 1678, in build
    raise BuildError(endpoint, values, method)
BuildError: ('amdin', {}, None)
